title: "PiC: Phrase in Context"
description: "A Dataset for Phrase Understanding and Semantic Search"
theme: jekyll-theme-cayman
# remote_theme: tuur29/pages-themes-cayman

google_analytics: "G-7SWKVJDDB4"
google_analytics_anonymize: false
darkmode: false
show_downloads: true

color:
    gradient_left: "#38A2D7"
    gradient_right: "#014871"
    header: "#fff"
    android_theme: "#000"     # this default to gradient_color
    link: "#1e6bb8"           # this default to gradient_color
    section_title: "#155799"  # this default to gradient_color

github:
    is_project_page: true
    repository_url: https://github.com/Phrase-in-Context
    
buttons:
    zip_url: https://huggingface.co/PiC     # https://auburn.edu/~tmp0038/PiC.zip
    zip_title: Download on Huggingface      # "Download PiC.zip (~196MB)"
    zip_hide: false
    tar_url: https://auburn.edu/~tmp0038/PiC.tar.gz
    tar_title: "Download PiC.tar.gz"
    tar_hide: true
    github_hide: false

# --- List of links in the navigation bar --- #

navbar-links:
    Paper: "https://arxiv.org/abs/2207.09068"
    Demo: "https://aub.ie/phrase-search"
    Phrase Similarity: "phrase_similarity"
    Phrase Retrieval: "phrase_retrieval"
    Phrase Sense Disambiguation: "phrase_sense_disambiguation"
    # Evaluation: "evaluation"

contact: "phrase-in-context@googlegroups.com"
google-group: "https://groups.google.com/u/1/g/phrase-in-context"

remove-ads: true

